name: JAVA-SNOW-CICD-POC

on:
  push:
    branches: [ "master", "develop","feature-createchange" ]
  pull_request:
    branches: [ "master", "develop", "feature-createchange"]

jobs: 
  publish-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn -B -DskipTests clean packag
    - run: mvn test -Dmaven.test.failure.ignore=true surefire-report:report
    - run: mkdir staging && cp target/*.jar staging && cp target/surefire-reports/*.xml staging 
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
