name: JAVA-SNOW-CICD-POC

on:
  push:
    branches: [ "master", "develop","feature-createchange" ]
  pull_request:
    branches: [ "master", "develop", "feature-createchange"]


jobs: 
  publish-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn -B -DskipTests clean package
    - run: mvn test

    - name: ServiceNow DevOps Unit Test Results
      uses: ServiceNow/servicenow-devops-test-report@v2.0.0
      with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}}
          job-name: 'publish-job'
          xml-report-filename: target/surefire-reports/testng-results.xml
