name: Upload

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          mkdir artifact
          echo $GITHUB_SHA > artifact/sha
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: artifact
